name: deploy to lambda
on: [push]

jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --target ./package
      - name: Generate Zip
        run: |
          cd package && zip -r ../deployment.zip . && cd ..
          zip -g deployment.zip *.py
      - name: default deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambda-function
          zip_file: deployment.zip
